# Dictionary of all schools on the GA milesplit website {School name : School milesplit link}
ga_milesplit_schools = {'A.R. Johnson Health Science and Engineering Magnet School': 'https://ga.milesplit.com/teams/29372-ar-johnson-health-science-and-engineering-magnet-school',
 'ACE Charter': 'https://ga.milesplit.com/teams/37735-ace-charter',
 'Abundant Life Christian Academy': 'https://ga.milesplit.com/teams/65256-abundant-life-christian-academy',
 'Abundant Life Christian Academy Middle School': 'https://ga.milesplit.com/teams/65258-abundant-life-christian-academy-middle-school',
 'Academe of the Oaks': 'https://ga.milesplit.com/teams/25784-academe-of-the-oaks',
 'Adairsville High School': 'https://ga.milesplit.com/teams/4393-adairsville-high-school',
 'Al Falah Academy': 'https://ga.milesplit.com/teams/45311-al-falah-academy',
 'Albany': 'https://ga.milesplit.com/teams/4394-albany',
 'Alcovy': 'https://ga.milesplit.com/teams/7249-alcovy',
 'Alexander': 'https://ga.milesplit.com/teams/4395-alexander',
 'Allatoona HS': 'https://ga.milesplit.com/teams/16360-allatoona-hs',
 'Alpharetta': 'https://ga.milesplit.com/teams/4396-alpharetta',
 'American  Heritage Academy': 'https://ga.milesplit.com/teams/16410-american-heritage-academy',
 'Apalachee High School': 'https://ga.milesplit.com/teams/6222-apalachee-high-school',
 'Appling Christian Academy': 'https://ga.milesplit.com/teams/44621-appling-christian-academy',
 'Appling County HS': 'https://ga.milesplit.com/teams/9053-appling-county-hs',
 'Aquinas': 'https://ga.milesplit.com/teams/9114-aquinas',
 'Arabia Mountain HS': 'https://ga.milesplit.com/teams/22821-arabia-mountain-hs',
 'Archer': 'https://ga.milesplit.com/teams/22701-archer',
 'Arlington Christian': 'https://ga.milesplit.com/teams/23739-arlington-christian',
 'Armuchee': 'https://ga.milesplit.com/teams/8895-armuchee',
 'Ash Tree Learning Center Academy': 'https://ga.milesplit.com/teams/41790-ash-tree-learning-center-academy',
 'Athens Academy': 'https://ga.milesplit.com/teams/4397-athens-academy',
 'Athens Christian': 'https://ga.milesplit.com/teams/4398-athens-christian',
 'Atkinson County HS': 'https://ga.milesplit.com/teams/9083-atkinson-county-hs',
 'Atlanta Adventist': 'https://ga.milesplit.com/teams/41607-atlanta-adventist',
 'Atlanta Area School for the Deaf': 'https://ga.milesplit.com/teams/25825-atlanta-area-school-for-the-deaf',
 'Atlanta Classical Academy': 'https://ga.milesplit.com/teams/37201-atlanta-classical-academy',
 'Atlanta Girls School': 'https://ga.milesplit.com/teams/23751-atlanta-girls-school',
 'Atlanta International School': 'https://ga.milesplit.com/teams/4501-atlanta-international-school',
 'Atlanta Public Schools': 'https://ga.milesplit.com/teams/6914-atlanta-public-schools',
 'Augusta Eagles HS': 'https://ga.milesplit.com/teams/37267-augusta-eagles-hs',
 'Augusta Prep': 'https://ga.milesplit.com/teams/23364-augusta-prep',
 'Augusta Prep HS': 'https://ga.milesplit.com/teams/23746-augusta-prep-hs',
 'Ave Maria': 'https://ga.milesplit.com/teams/66130-ave-maria',
 'Avondale': 'https://ga.milesplit.com/teams/4671-avondale',
 'B.E.S.T. Academy High School': 'https://ga.milesplit.com/teams/29567-best-academy-high-school',
 'Bacon County HS': 'https://ga.milesplit.com/teams/9084-bacon-county-hs',
 'Baconton Charter': 'https://ga.milesplit.com/teams/9077-baconton-charter',
 'Bainbridge High School': 'https://ga.milesplit.com/teams/4362-bainbridge-high-school',
 'Baker County HS': 'https://ga.milesplit.com/teams/26776-baker-county-hs',
 'Baldwin High School': 'https://ga.milesplit.com/teams/34769-baldwin-high-school',
 'Banks County HS': 'https://ga.milesplit.com/teams/9073-banks-county-hs',
 'Banneker': 'https://ga.milesplit.com/teams/4399-banneker',
 'Barrow Arts & Sciences Academy': 'https://ga.milesplit.com/teams/51181-barrow-arts-and-sciences-academy',
 'Bass High School': 'https://ga.milesplit.com/teams/57224-bass-high-school',
 'Beach': 'https://ga.milesplit.com/teams/4400-beach',
 'Bearcreek MS': 'https://ga.milesplit.com/teams/25847-bearcreek-ms',
 'Ben Franklin Academy': 'https://ga.milesplit.com/teams/23670-ben-franklin-academy',
 'Benedictine Military School': 'https://ga.milesplit.com/teams/12121-benedictine-military-school',
 'Berkmar High School': 'https://ga.milesplit.com/teams/4372-berkmar-high-school',
 'Berrien County HS': 'https://ga.milesplit.com/teams/9049-berrien-county-hs',
 'Bethesda Academy': 'https://ga.milesplit.com/teams/25889-bethesda-academy',
 'Bethlehem Christian': 'https://ga.milesplit.com/teams/18796-bethlehem-christian',
 'Bible Baptist Christian Academy': 'https://ga.milesplit.com/teams/68138-bible-baptist-christian-academy',
 'Bible Baptist School': 'https://ga.milesplit.com/teams/38942-bible-baptist-school',
 'Bleckley County High School': 'https://ga.milesplit.com/teams/4402-bleckley-county-high-school',
 'Blessed Sacrament School': 'https://ga.milesplit.com/teams/23152-blessed-sacrament-school',
 'Blessed Trinity': 'https://ga.milesplit.com/teams/4401-blessed-trinity',
 'Booker T. Washington': 'https://ga.milesplit.com/teams/4523-booker-t-washington',
 'Bowdon': 'https://ga.milesplit.com/teams/9104-bowdon',
 'Bradwell Institute': 'https://ga.milesplit.com/teams/4632-bradwell-institute',
 'Brandon Hall School': 'https://ga.milesplit.com/teams/23735-brandon-hall-school',
 'Brantley County HS': 'https://ga.milesplit.com/teams/9054-brantley-county-hs',
 'Brava Total Praise Performance': 'https://ga.milesplit.com/teams/27793-brava-total-praise-performance',
 'Bremen High School': 'https://ga.milesplit.com/teams/4525-bremen-high-school',
 'Brenau Academy': 'https://ga.milesplit.com/teams/25821-brenau-academy',
 'Brentwood School': 'https://ga.milesplit.com/teams/23733-brentwood-school',
 'Briarwood Academy': 'https://ga.milesplit.com/teams/26372-briarwood-academy',
 'Brooks County High School': 'https://ga.milesplit.com/teams/4497-brooks-county-high-school',
 'Brookstone': 'https://ga.milesplit.com/teams/4403-brookstone',
 'Brookwood': 'https://ga.milesplit.com/teams/4328-brookwood',
 'Brookwood High School': 'https://ga.milesplit.com/teams/70001-brookwood-high-school',
 'Brookwood School': 'https://ga.milesplit.com/teams/7665-brookwood-school',
 'Broxton High School': 'https://ga.milesplit.com/teams/57234-broxton-high-school',
 'Brunswick': 'https://ga.milesplit.com/teams/4404-brunswick',
 'Bryan County HS': 'https://ga.milesplit.com/teams/8352-bryan-county-hs',
 'Buford High School': 'https://ga.milesplit.com/teams/4466-buford-high-school',
 'Bulloch Academy': 'https://ga.milesplit.com/teams/15470-bulloch-academy',
 'Burke County': 'https://ga.milesplit.com/teams/4405-burke-county',
 'Butler': 'https://ga.milesplit.com/teams/9043-butler',
 "C.H.E.S.S. Academy-Chad O'Quinn": 'https://ga.milesplit.com/teams/57158-chess-academy-chad-oquinn',
 'CORE Community School': 'https://ga.milesplit.com/teams/53642-core-community-school',
 'Cairo': 'https://ga.milesplit.com/teams/4406-cairo',
 'Calhoun': 'https://ga.milesplit.com/teams/6138-calhoun',
 'Calhoun County HS': 'https://ga.milesplit.com/teams/9078-calhoun-county-hs',
 'Callaway High School': 'https://ga.milesplit.com/teams/9061-callaway-high-school',
 'Calvary Christian School': 'https://ga.milesplit.com/teams/23750-calvary-christian-school',
 'Calvary Day School': 'https://ga.milesplit.com/teams/9096-calvary-day-school',
 'Cambridge HS': 'https://ga.milesplit.com/teams/30478-cambridge-hs',
 'Camden County HS': 'https://ga.milesplit.com/teams/7011-camden-county-hs',
 'Camp Patten': 'https://ga.milesplit.com/teams/65330-camp-patten',
 'Campbell High School': 'https://ga.milesplit.com/teams/4375-campbell-high-school',
 'Carrollton High School': 'https://ga.milesplit.com/teams/4355-carrollton-high-school',
 'Cartersville High School': 'https://ga.milesplit.com/teams/4407-cartersville-high-school',
 'Carver Atlanta': 'https://ga.milesplit.com/teams/4680-carver-atlanta',
 'Cass High School': 'https://ga.milesplit.com/teams/5876-cass-high-school',
 'Cedar Grove': 'https://ga.milesplit.com/teams/4408-cedar-grove',
 'Cedar Shoals': 'https://ga.milesplit.com/teams/4409-cedar-shoals',
 'Cedartown': 'https://ga.milesplit.com/teams/8368-cedartown',
 'Centennial': 'https://ga.milesplit.com/teams/4410-centennial',
 'Central Christian School': 'https://ga.milesplit.com/teams/47187-central-christian-school',
 'Central Fellowship Christian Academy': 'https://ga.milesplit.com/teams/18959-central-fellowship-christian-academy',
 'Central Georgia Athletics': 'https://ga.milesplit.com/teams/40431-central-georgia-athletics',
 'Central Gwinnett': 'https://ga.milesplit.com/teams/4411-central-gwinnett',
 'Central High School': 'https://ga.milesplit.com/teams/8504-central-high-school',
 'Central Macon': 'https://ga.milesplit.com/teams/7659-central-macon',
 'Central Talbotton': 'https://ga.milesplit.com/teams/9098-central-talbotton',
 'Challenge Charter': 'https://ga.milesplit.com/teams/30485-challenge-charter',
 'Chamblee': 'https://ga.milesplit.com/teams/4412-chamblee',
 'Chapel Hill High School': 'https://ga.milesplit.com/teams/4367-chapel-hill-high-school',
 'Charles Drew HS': 'https://ga.milesplit.com/teams/25807-charles-drew-hs',
 'Charlton County': 'https://ga.milesplit.com/teams/8360-charlton-county',
 'Chatham Academy': 'https://ga.milesplit.com/teams/23153-chatham-academy',
 'Chattahoochee County': 'https://ga.milesplit.com/teams/9099-chattahoochee-county',
 'Chattahoochee High School': 'https://ga.milesplit.com/teams/4413-chattahoochee-high-school',
 'Chattooga HS': 'https://ga.milesplit.com/teams/15961-chattooga-hs',
 'Cherokee Bluff High School': 'https://ga.milesplit.com/teams/44944-cherokee-bluff-high-school',
 'Cherokee Christian Schools': 'https://ga.milesplit.com/teams/43589-cherokee-christian-schools',
 'Cherokee High School': 'https://ga.milesplit.com/teams/4414-cherokee-high-school',
 'Chestatee': 'https://ga.milesplit.com/teams/5880-chestatee',
 'Chesterton Academy of Atlanta': 'https://ga.milesplit.com/teams/72859-chesterton-academy-of-atlanta',
 'Christian Heritage School': 'https://ga.milesplit.com/teams/30484-christian-heritage-school',
 'Chrysalis Experiential Academy Rowsell': 'https://ga.milesplit.com/teams/25796-chrysalis-experiential-academy-rowsell',
 "Citizen's Christian": 'https://ga.milesplit.com/teams/23738-citizens-christian',
 "Citizen's Christian Academy": 'https://ga.milesplit.com/teams/29001-citizens-christian-academy',
 'Citizens Christian Academy': 'https://ga.milesplit.com/teams/70283-citizens-christian-academy',
 'Clarke Central': 'https://ga.milesplit.com/teams/4171-clarke-central',
 'Clarkston': 'https://ga.milesplit.com/teams/4475-clarkston',
 'Claxton High School': 'https://ga.milesplit.com/teams/8366-claxton-high-school',
 'Cliff Valley School': 'https://ga.milesplit.com/teams/41161-cliff-valley-school',
 'Clinch County HS': 'https://ga.milesplit.com/teams/9085-clinch-county-hs',
 'Coahulla Creek HS': 'https://ga.milesplit.com/teams/29157-coahulla-creek-hs',
 'Coastal Homeschool Athletic Association HS': 'https://ga.milesplit.com/teams/67954-coastal-homeschool-athletic-association-hs',
 'Coffee HS': 'https://ga.milesplit.com/teams/4836-coffee-hs',
 'Collins Hill High School': 'https://ga.milesplit.com/teams/4160-collins-hill-high-school',
 'Colonial Hills Christian School': 'https://ga.milesplit.com/teams/36315-colonial-hills-christian-school',
 'Colquitt Christian Academy': 'https://ga.milesplit.com/teams/49093-colquitt-christian-academy',
 'Colquitt County': 'https://ga.milesplit.com/teams/4835-colquitt-county',
 'Columbia High School': 'https://ga.milesplit.com/teams/4491-columbia-high-school',
 'Columbus High School': 'https://ga.milesplit.com/teams/4462-columbus-high-school',
 'Commerce': 'https://ga.milesplit.com/teams/7067-commerce',
 'Community Christian Academy (Adel)': 'https://ga.milesplit.com/teams/43901-community-christian-academy-adel',
 'Community Christian Academy (Martinez)': 'https://ga.milesplit.com/teams/37190-community-christian-academy-martinez',
 'Community Christian School': 'https://ga.milesplit.com/teams/18967-community-christian-school',
 'Cook County High School': 'https://ga.milesplit.com/teams/7012-cook-county-high-school',
 'Coosa HS': 'https://ga.milesplit.com/teams/6139-coosa-hs',
 "Coretta Scott King Young Women's Leadership Academy": 'https://ga.milesplit.com/teams/27461-coretta-scott-king-young-womens-leadership-academy',
 'Cornerstone Prep Academy': 'https://ga.milesplit.com/teams/28865-cornerstone-prep-academy',
 'Cornerstone Schools HS': 'https://ga.milesplit.com/teams/51148-cornerstone-schools-hs',
 'Cornerstone Track and Athletic Association': 'https://ga.milesplit.com/teams/28911-cornerstone-track-and-athletic-association',
 'Covenant Academy': 'https://ga.milesplit.com/teams/18964-covenant-academy',
 'Covenant Christian Academy': 'https://ga.milesplit.com/teams/27558-covenant-christian-academy',
 'Covenant Christian School (Cedartown)': 'https://ga.milesplit.com/teams/72491-covenant-christian-school-cedartown',
 'Covington Academy': 'https://ga.milesplit.com/teams/37134-covington-academy',
 'Cox Academy': 'https://ga.milesplit.com/teams/66775-cox-academy',
 'Crawford County': 'https://ga.milesplit.com/teams/9062-crawford-county',
 'Crawford County MS': 'https://ga.milesplit.com/teams/22700-crawford-county-ms',
 'Creekside': 'https://ga.milesplit.com/teams/4415-creekside',
 'Creekside Christian Academy': 'https://ga.milesplit.com/teams/27604-creekside-christian-academy',
 'Creekview': 'https://ga.milesplit.com/teams/9066-creekview',
 'Crestwood High School': 'https://ga.milesplit.com/teams/57233-crestwood-high-school',
 'Crim': 'https://ga.milesplit.com/teams/4416-crim',
 'Crisp Academy': 'https://ga.milesplit.com/teams/23744-crisp-academy',
 'Crisp County': 'https://ga.milesplit.com/teams/4833-crisp-county',
 'Cristo Rey Jesuit HS': 'https://ga.milesplit.com/teams/37650-cristo-rey-jesuit-hs',
 'Cross Creek': 'https://ga.milesplit.com/teams/8370-cross-creek',
 'Cross Keys': 'https://ga.milesplit.com/teams/4653-cross-keys',
 'Crosspointe Christian Academy': 'https://ga.milesplit.com/teams/37969-crosspointe-christian-academy',
 'Crossroads Christian Academy': 'https://ga.milesplit.com/teams/46304-crossroads-christian-academy',
 'Cumberland Academy of Georgia': 'https://ga.milesplit.com/teams/29047-cumberland-academy-of-georgia',
 'Cumberland Christian Academy': 'https://ga.milesplit.com/teams/39637-cumberland-christian-academy',
 'Curtis Baptist School': 'https://ga.milesplit.com/teams/26377-curtis-baptist-school',
 'Dacula': 'https://ga.milesplit.com/teams/4391-dacula',
 'Dade County HS': 'https://ga.milesplit.com/teams/9069-dade-county-hs',
 'Dalton High School': 'https://ga.milesplit.com/teams/4492-dalton-high-school',
 'Dar-Un-Noor Academy': 'https://ga.milesplit.com/teams/49606-dar-un-noor-academy',
 'Darlington School': 'https://ga.milesplit.com/teams/4417-darlington-school',
 'David Emanuel Academy': 'https://ga.milesplit.com/teams/23740-david-emanuel-academy',
 'Dawson County': 'https://ga.milesplit.com/teams/8472-dawson-county',
 'Dawson Street Christian Academy': 'https://ga.milesplit.com/teams/26373-dawson-street-christian-academy',
 'Decatur High School': 'https://ga.milesplit.com/teams/4366-decatur-high-school',
 'Deerfield-Windsor School': 'https://ga.milesplit.com/teams/12124-deerfield-windsor-school',
 'Dekalb School of the Arts': 'https://ga.milesplit.com/teams/56091-dekalb-school-of-the-arts',
 'Denmark High School': 'https://ga.milesplit.com/teams/44732-denmark-high-school',
 'Discovery HS': 'https://ga.milesplit.com/teams/38594-discovery-hs',
 'Dodge County High School': 'https://ga.milesplit.com/teams/8744-dodge-county-high-school',
 'Dominion Christian': 'https://ga.milesplit.com/teams/23748-dominion-christian',
 'Dooly County HS': 'https://ga.milesplit.com/teams/9089-dooly-county-hs',
 'Dougherty': 'https://ga.milesplit.com/teams/4423-dougherty',
 'Douglas County': 'https://ga.milesplit.com/teams/4424-douglas-county',
 'Dresden Elementary': 'https://ga.milesplit.com/teams/72640-dresden-elementary',
 'Drew Charter Senior Academy': 'https://ga.milesplit.com/teams/35792-drew-charter-senior-academy',
 'Druid Hills': 'https://ga.milesplit.com/teams/4426-druid-hills',
 'Dublin High School': 'https://ga.milesplit.com/teams/7055-dublin-high-school',
 'Duluth High School': 'https://ga.milesplit.com/teams/4164-duluth-high-school',
 'Dunwoody': 'https://ga.milesplit.com/teams/4427-dunwoody',
 'Dutchtown High School': 'https://ga.milesplit.com/teams/8390-dutchtown-high-school',
 "Eagle's Landing Christian Academy MS": 'https://ga.milesplit.com/teams/50474-eagles-landing-christian-academy-ms',
 "Eagle's Landing High School": 'https://ga.milesplit.com/teams/4428-eagles-landing-high-school',
 'Eagles Landing Christian Academy': 'https://ga.milesplit.com/teams/6883-eagles-landing-christian-academy',
 'Early County': 'https://ga.milesplit.com/teams/7097-early-county',
 'East Coweta': 'https://ga.milesplit.com/teams/4429-east-coweta',
 'East Forsyth High School': 'https://ga.milesplit.com/teams/53150-east-forsyth-high-school',
 'East Hall HS': 'https://ga.milesplit.com/teams/9048-east-hall-hs',
 'East Jackson High School': 'https://ga.milesplit.com/teams/12115-east-jackson-high-school',
 'East Laurens High School': 'https://ga.milesplit.com/teams/7098-east-laurens-high-school',
 'East Paulding High School': 'https://ga.milesplit.com/teams/4430-east-paulding-high-school',
 'Eastside': 'https://ga.milesplit.com/teams/4744-eastside',
 'Eastside Christian School': 'https://ga.milesplit.com/teams/28967-eastside-christian-school',
 'Echols County HS': 'https://ga.milesplit.com/teams/9086-echols-county-hs',
 'Eddie White Academy': 'https://ga.milesplit.com/teams/32668-eddie-white-academy',
 'Edmund Burke Academy': 'https://ga.milesplit.com/teams/23734-edmund-burke-academy',
 'Effingham County': 'https://ga.milesplit.com/teams/7109-effingham-county',
 'Elbert County High School': 'https://ga.milesplit.com/teams/4431-elbert-county-high-school',
 'Elite Scholars Academy': 'https://ga.milesplit.com/teams/29559-elite-scholars-academy',
 'Emanuel County Institute': 'https://ga.milesplit.com/teams/26779-emanuel-county-institute',
 'Etowah': 'https://ga.milesplit.com/teams/4432-etowah',
 'Evans High School': 'https://ga.milesplit.com/teams/4433-evans-high-school',
 'Excel Christian': 'https://ga.milesplit.com/teams/9105-excel-christian',
 'Fairmount High School': 'https://ga.milesplit.com/teams/57229-fairmount-high-school',
 'Faith Christain School': 'https://ga.milesplit.com/teams/57687-faith-christain-school',
 'Fannin County HS': 'https://ga.milesplit.com/teams/9074-fannin-county-hs',
 'Favor Transition Academy': 'https://ga.milesplit.com/teams/72447-favor-transition-academy',
 'Fayette County': 'https://ga.milesplit.com/teams/4434-fayette-county',
 'Feldwood High School': 'https://ga.milesplit.com/teams/57236-feldwood-high-school',
 'Fellowship Christian School': 'https://ga.milesplit.com/teams/7637-fellowship-christian-school',
 'Fideles Christian School': 'https://ga.milesplit.com/teams/41515-fideles-christian-school',
 'First Presbyterian Christian Academy': 'https://ga.milesplit.com/teams/31236-first-presbyterian-christian-academy',
 'First Presbyterian Day School': 'https://ga.milesplit.com/teams/7651-first-presbyterian-day-school',
 'Fitzgerald': 'https://ga.milesplit.com/teams/9050-fitzgerald',
 'Flint River Academy': 'https://ga.milesplit.com/teams/25959-flint-river-academy',
 'Flowery Branch': 'https://ga.milesplit.com/teams/5879-flowery-branch',
 'Forest Park': 'https://ga.milesplit.com/teams/52950-forest-park',
 'Forsyth Central': 'https://ga.milesplit.com/teams/7667-forsyth-central',
 'Franklin County High School': 'https://ga.milesplit.com/teams/4371-franklin-county-high-school',
 'Frederica Academy': 'https://ga.milesplit.com/teams/18955-frederica-academy',
 'Frederick Douglass': 'https://ga.milesplit.com/teams/4425-frederick-douglass',
 'Friendship Christian School': 'https://ga.milesplit.com/teams/72775-friendship-christian-school',
 'Friendship Christian School Elementary': 'https://ga.milesplit.com/teams/72773-friendship-christian-school-elementary',
 'Friendship Christian School MS': 'https://ga.milesplit.com/teams/72774-friendship-christian-school-ms',
 'Fugees Academy': 'https://ga.milesplit.com/teams/40636-fugees-academy',
 'Fullington Academy': 'https://ga.milesplit.com/teams/26376-fullington-academy',
 'Fulton Leadership Academy': 'https://ga.milesplit.com/teams/29463-fulton-leadership-academy',
 'Fulton Science Academy': 'https://ga.milesplit.com/teams/29609-fulton-science-academy',
 'Furlow Charter School': 'https://ga.milesplit.com/teams/40359-furlow-charter-school',
 'Furtah Preparatory School': 'https://ga.milesplit.com/teams/41488-furtah-preparatory-school',
 'G.W. Carver, Columbus': 'https://ga.milesplit.com/teams/7132-gw-carver-columbus',
 'GHSA Sectional Meets': 'https://ga.milesplit.com/teams/72985-ghsa-sectional-meets',
 'Ga.MileSplit': 'https://ga.milesplit.com/teams/15501-gamilesplit',
 'Gables Academy': 'https://ga.milesplit.com/teams/25824-gables-academy',
 'Gainesville High School': 'https://ga.milesplit.com/teams/6221-gainesville-high-school',
 'Galloway': 'https://ga.milesplit.com/teams/5967-galloway',
 'Gatewood Schools': 'https://ga.milesplit.com/teams/18962-gatewood-schools',
 'Genesis Academy': 'https://ga.milesplit.com/teams/34724-genesis-academy',
 'Genesis Innovation Academy': 'https://ga.milesplit.com/teams/56092-genesis-innovation-academy',
 'George Walton Academy': 'https://ga.milesplit.com/teams/18957-george-walton-academy',
 'Georgia Academy for the Blind': 'https://ga.milesplit.com/teams/9109-georgia-academy-for-the-blind',
 'Georgia Christian': 'https://ga.milesplit.com/teams/7656-georgia-christian',
 'Georgia Connections Academy': 'https://ga.milesplit.com/teams/38307-georgia-connections-academy',
 'Georgia Cumberland Academy': 'https://ga.milesplit.com/teams/34723-georgia-cumberland-academy',
 'Georgia High School Association': 'https://ga.milesplit.com/teams/68996-georgia-high-school-association',
 'Georgia Military College': 'https://ga.milesplit.com/teams/26874-georgia-military-college',
 'Georgia Military College Prep School': 'https://ga.milesplit.com/teams/9110-georgia-military-college-prep-school',
 'Georgia School for Innovation and Classics High School': 'https://ga.milesplit.com/teams/52457-georgia-school-for-innovation-and-classics-high-school',
 'Gilmer High': 'https://ga.milesplit.com/teams/6899-gilmer-high',
 'Glascock County HS': 'https://ga.milesplit.com/teams/9115-glascock-county-hs',
 'Glenn Hills': 'https://ga.milesplit.com/teams/8350-glenn-hills',
 'Glynn Academy': 'https://ga.milesplit.com/teams/4634-glynn-academy',
 'Gordon Central High School': 'https://ga.milesplit.com/teams/4292-gordon-central-high-school',
 'Gordon Lee High School': 'https://ga.milesplit.com/teams/8354-gordon-lee-high-school',
 'Grace Baptist Christian School': 'https://ga.milesplit.com/teams/29089-grace-baptist-christian-school',
 'Grace Christian Academy': 'https://ga.milesplit.com/teams/22275-grace-christian-academy',
 'Grace Christian Academy (Fayetteville)': 'https://ga.milesplit.com/teams/37798-grace-christian-academy-fayetteville',
 'Grayson High School': 'https://ga.milesplit.com/teams/4436-grayson-high-school',
 'Greater Atlanta Adventist Academy': 'https://ga.milesplit.com/teams/39754-greater-atlanta-adventist-academy',
 'Greater Atlanta Christian': 'https://ga.milesplit.com/teams/4437-greater-atlanta-christian',
 'Greenbrier High School': 'https://ga.milesplit.com/teams/4163-greenbrier-high-school',
 'Greene County HS': 'https://ga.milesplit.com/teams/7009-greene-county-hs',
 'Greenforest Christian Academy': 'https://ga.milesplit.com/teams/15518-greenforest-christian-academy',
 'Greenville HS': 'https://ga.milesplit.com/teams/9100-greenville-hs',
 'Griffin': 'https://ga.milesplit.com/teams/4438-griffin',
 'Groves': 'https://ga.milesplit.com/teams/6908-groves',
 'Grovetown HS': 'https://ga.milesplit.com/teams/22320-grovetown-hs',
 'HALO Wolfpack': 'https://ga.milesplit.com/teams/54757-halo-wolfpack',
 'HALO Wolfpack Middle School': 'https://ga.milesplit.com/teams/54758-halo-wolfpack-middle-school',
 'HCHS Braves': 'https://ga.milesplit.com/teams/70994-hchs-braves',
 'HV Jenkins': 'https://ga.milesplit.com/teams/7008-hv-jenkins',
 'Habersham Central High School': 'https://ga.milesplit.com/teams/4173-habersham-central-high-school',
 'Habersham School': 'https://ga.milesplit.com/teams/27532-habersham-school',
 'Hampton HS': 'https://ga.milesplit.com/teams/37093-hampton-hs',
 'Hampton,GA': 'https://ga.milesplit.com/teams/15414-hamptonga',
 'Hancock Central': 'https://ga.milesplit.com/teams/9111-hancock-central',
 'Hapeville Charter Career Academy': 'https://ga.milesplit.com/teams/26780-hapeville-charter-career-academy',
 'Haralson County HS': 'https://ga.milesplit.com/teams/9047-haralson-county-hs',
 'Hardaway': 'https://ga.milesplit.com/teams/6898-hardaway',
 'Harlem HS': 'https://ga.milesplit.com/teams/8466-harlem-hs',
 'Harps Crossing Christian Academy': 'https://ga.milesplit.com/teams/67647-harps-crossing-christian-academy',
 'Harris Co. High School': 'https://ga.milesplit.com/teams/5965-harris-co-high-school',
 'Harrison High School': 'https://ga.milesplit.com/teams/4162-harrison-high-school',
 'Hart County': 'https://ga.milesplit.com/teams/4657-hart-county',
 'Harvester Christian Academy': 'https://ga.milesplit.com/teams/21316-harvester-christian-academy',
 'Hawkinsville HS': 'https://ga.milesplit.com/teams/9090-hawkinsville-hs',
 'Headland High School': 'https://ga.milesplit.com/teams/57223-headland-high-school',
 'Heard County HS': 'https://ga.milesplit.com/teams/9063-heard-county-hs',
 'Hebron Christian': 'https://ga.milesplit.com/teams/9127-hebron-christian',
 'Hebron Christian Academy': 'https://ga.milesplit.com/teams/47124-hebron-christian-academy',
 'Heirway Christian Academy': 'https://ga.milesplit.com/teams/43828-heirway-christian-academy',
 'Henry County High School': 'https://ga.milesplit.com/teams/57254-henry-county-high-school',
 'Hephzibah': 'https://ga.milesplit.com/teams/7104-hephzibah',
 'Heritage Academy': 'https://ga.milesplit.com/teams/38911-heritage-academy',
 'Heritage Christian Academy': 'https://ga.milesplit.com/teams/37670-heritage-christian-academy',
 'Heritage Christian School': 'https://ga.milesplit.com/teams/31239-heritage-christian-school',
 'Heritage HS, Catoosa': 'https://ga.milesplit.com/teams/16396-heritage-hs-catoosa',
 'Heritage High School': 'https://ga.milesplit.com/teams/4660-heritage-high-school',
 'Heritage Prep': 'https://ga.milesplit.com/teams/27450-heritage-prep',
 'Highland Christian Academy': 'https://ga.milesplit.com/teams/28838-highland-christian-academy',
 'Highland Running Club': 'https://ga.milesplit.com/teams/69340-highland-running-club',
 'Hill Academy': 'https://ga.milesplit.com/teams/51007-hill-academy',
 'Hillgrove': 'https://ga.milesplit.com/teams/7679-hillgrove',
 'Hiram High School': 'https://ga.milesplit.com/teams/4305-hiram-high-school',
 'Hogansville High School': 'https://ga.milesplit.com/teams/57237-hogansville-high-school',
 "Holy Innocents' Episcopal School": 'https://ga.milesplit.com/teams/4465-holy-innocents-episcopal-school',
 'Holy Spirit Preparatory': 'https://ga.milesplit.com/teams/23745-holy-spirit-preparatory',
 'Horizon Christian Academy': 'https://ga.milesplit.com/teams/30193-horizon-christian-academy',
 'Houston County': 'https://ga.milesplit.com/teams/7638-houston-county',
 'Howard High School': 'https://ga.milesplit.com/teams/18847-howard-high-school',
 'Irwin County': 'https://ga.milesplit.com/teams/8372-irwin-county',
 'Islands High School': 'https://ga.milesplit.com/teams/26781-islands-high-school',
 'Jackson County': 'https://ga.milesplit.com/teams/4743-jackson-county',
 'Jackson HS': 'https://ga.milesplit.com/teams/9045-jackson-hs',
 'Jasper County HS': 'https://ga.milesplit.com/teams/9112-jasper-county-hs',
 'Jeff Davis': 'https://ga.milesplit.com/teams/7036-jeff-davis',
 'Jefferson County HS': 'https://ga.milesplit.com/teams/9058-jefferson-county-hs',
 'Jefferson High School': 'https://ga.milesplit.com/teams/4174-jefferson-high-school',
 'Jenkins Co. High School': 'https://ga.milesplit.com/teams/4633-jenkins-co-high-school',
 'Jenkins County HS': 'https://ga.milesplit.com/teams/65332-jenkins-county-hs',
 'John B. Gordon School (Closed 1995)': 'https://ga.milesplit.com/teams/34625-john-b-gordon-school-closed-1995',
 'John Hancock Academy': 'https://ga.milesplit.com/teams/26375-john-hancock-academy',
 'John Milledge Academy': 'https://ga.milesplit.com/teams/20280-john-milledge-academy',
 'John Robert Lewis Elementary': 'https://ga.milesplit.com/teams/72639-john-robert-lewis-elementary',
 'Johns Creek HS': 'https://ga.milesplit.com/teams/22070-johns-creek-hs',
 'Johnson County': 'https://ga.milesplit.com/teams/4631-johnson-county',
 'Johnson Ferry Christian Academy': 'https://ga.milesplit.com/teams/28843-johnson-ferry-christian-academy',
 'Johnson HS': 'https://ga.milesplit.com/teams/8507-johnson-hs',
 'Johnson-Savannah': 'https://ga.milesplit.com/teams/9030-johnson-savannah',
 'Jones County High School': 'https://ga.milesplit.com/teams/4450-jones-county-high-school',
 'Jonesboro HS': 'https://ga.milesplit.com/teams/4667-jonesboro-hs',
 'Jordan': 'https://ga.milesplit.com/teams/7101-jordan',
 'Josey': 'https://ga.milesplit.com/teams/8363-josey',
 'KIPP Atlanta Collegiate': 'https://ga.milesplit.com/teams/28848-kipp-atlanta-collegiate',
 'Kell High School': 'https://ga.milesplit.com/teams/5923-kell-high-school',
 'Kendrick': 'https://ga.milesplit.com/teams/7105-kendrick',
 'Kennesaw Mountain': 'https://ga.milesplit.com/teams/4453-kennesaw-mountain',
 'Killian Hill Christian School': 'https://ga.milesplit.com/teams/41183-killian-hill-christian-school',
 "King's Ridge Christian School": 'https://ga.milesplit.com/teams/19011-kings-ridge-christian-school',
 'King’s Way Christian School': 'https://ga.milesplit.com/teams/46354-kings-way-christian-school',
 'Konos Academy': 'https://ga.milesplit.com/teams/40484-konos-academy',
 'LaFayette High School': 'https://ga.milesplit.com/teams/6136-lafayette-high-school',
 'LaGrange Academy': 'https://ga.milesplit.com/teams/25960-lagrange-academy',
 'LaGrange High School': 'https://ga.milesplit.com/teams/5873-lagrange-high-school',
 'Lafayette Christian School': 'https://ga.milesplit.com/teams/31158-lafayette-christian-school',
 'Lake Oconee Academy': 'https://ga.milesplit.com/teams/38895-lake-oconee-academy',
 'Lakeside Evans': 'https://ga.milesplit.com/teams/4448-lakeside-evans',
 'Lakeside HS DeKalb': 'https://ga.milesplit.com/teams/631-lakeside-hs-dekalb',
 'Lakeview Academy': 'https://ga.milesplit.com/teams/9129-lakeview-academy',
 'Lakeview-Fort Oglethorpe': 'https://ga.milesplit.com/teams/5885-lakeview-fort-oglethorpe',
 'Lamar County High School': 'https://ga.milesplit.com/teams/4520-lamar-county-high-school',
 'Lamar County MS': 'https://ga.milesplit.com/teams/18719-lamar-county-ms',
 'Lambert HS': 'https://ga.milesplit.com/teams/20840-lambert-hs',
 'Landmark Christian Elementary': 'https://ga.milesplit.com/teams/40037-landmark-christian-elementary',
 'Landmark Christian School': 'https://ga.milesplit.com/teams/4439-landmark-christian-school',
 'Laney': 'https://ga.milesplit.com/teams/8359-laney',
 'Langston Hughes HS': 'https://ga.milesplit.com/teams/23484-langston-hughes-hs',
 'Lanier Christian Academy': 'https://ga.milesplit.com/teams/40575-lanier-christian-academy',
 'Lanier County HS': 'https://ga.milesplit.com/teams/9087-lanier-county-hs',
 'Lanier HS': 'https://ga.milesplit.com/teams/26782-lanier-hs',
 'Lassiter High School': 'https://ga.milesplit.com/teams/4330-lassiter-high-school',
 'Lee County': 'https://ga.milesplit.com/teams/4834-lee-county',
 'Liberty County': 'https://ga.milesplit.com/teams/4635-liberty-county',
 'Lighthouse Classical Academy': 'https://ga.milesplit.com/teams/40566-lighthouse-classical-academy',
 'Lincoln County HS': 'https://ga.milesplit.com/teams/16109-lincoln-county-hs',
 'Lithia Springs': 'https://ga.milesplit.com/teams/4659-lithia-springs',
 'Lithonia High School': 'https://ga.milesplit.com/teams/4470-lithonia-high-school',
 'Locust Grove High School': 'https://ga.milesplit.com/teams/22265-locust-grove-high-school',
 'Loganville Christian Academy': 'https://ga.milesplit.com/teams/23749-loganville-christian-academy',
 'Loganville HS': 'https://ga.milesplit.com/teams/5945-loganville-hs',
 'Long County HS': 'https://ga.milesplit.com/teams/9055-long-county-hs',
 'Lovejoy': 'https://ga.milesplit.com/teams/4444-lovejoy',
 'Lovett': 'https://ga.milesplit.com/teams/4156-lovett',
 'Lovett MS': 'https://ga.milesplit.com/teams/41531-lovett-ms',
 'Lowndes High School': 'https://ga.milesplit.com/teams/4493-lowndes-high-school',
 'Luella High School': 'https://ga.milesplit.com/teams/5915-luella-high-school',
 'Lumpkin Co. High School': 'https://ga.milesplit.com/teams/5966-lumpkin-co-high-school',
 'Lyndon Academy': 'https://ga.milesplit.com/teams/36351-lyndon-academy',
 'M. Hoke Smith High school': 'https://ga.milesplit.com/teams/57243-m-hoke-smith-high-school',
 'MLK': 'https://ga.milesplit.com/teams/14687-mlk',
 'Macon County': 'https://ga.milesplit.com/teams/4519-macon-county',
 'Madison County HS': 'https://ga.milesplit.com/teams/8497-madison-county-hs',
 'Manchester': 'https://ga.milesplit.com/teams/8369-manchester',
 'Marietta High School': 'https://ga.milesplit.com/teams/4333-marietta-high-school',
 'Marion County HS': 'https://ga.milesplit.com/teams/7696-marion-county-hs',
 'Marist': 'https://ga.milesplit.com/teams/4392-marist',
 'Mary Persons': 'https://ga.milesplit.com/teams/7103-mary-persons',
 'Maynard H. Jackson High School': 'https://ga.milesplit.com/teams/4524-maynard-h-jackson-high-school',
 'Mays High School': 'https://ga.milesplit.com/teams/4170-mays-high-school',
 'McDonough': 'https://ga.milesplit.com/teams/15409-mcdonough',
 'McEachern High School': 'https://ga.milesplit.com/teams/4161-mceachern-high-school',
 'McIntosh County Academy': 'https://ga.milesplit.com/teams/7096-mcintosh-county-academy',
 'McIntosh High School': 'https://ga.milesplit.com/teams/4389-mcintosh-high-school',
 'McNair High School': 'https://ga.milesplit.com/teams/4489-mcnair-high-school',
 'Meadowcreek HS': 'https://ga.milesplit.com/teams/14763-meadowcreek-hs',
 'Memorial Day School': 'https://ga.milesplit.com/teams/30143-memorial-day-school',
 'Mercer Middle School': 'https://ga.milesplit.com/teams/69575-mercer-middle-school',
 'Metter': 'https://ga.milesplit.com/teams/9059-metter',
 'Midtown': 'https://ga.milesplit.com/teams/4390-midtown',
 'Midtown International School': 'https://ga.milesplit.com/teams/43829-midtown-international-school',
 'Mill Creek High School': 'https://ga.milesplit.com/teams/4157-mill-creek-high-school',
 'Mill Springs Academy': 'https://ga.milesplit.com/teams/23742-mill-springs-academy',
 'Miller County': 'https://ga.milesplit.com/teams/66993-miller-county',
 'Miller County HS': 'https://ga.milesplit.com/teams/9079-miller-county-hs',
 'Miller Grove High School': 'https://ga.milesplit.com/teams/5952-miller-grove-high-school',
 "Miller's Military Academy": 'https://ga.milesplit.com/teams/41510-millers-military-academy',
 'Milton High School': 'https://ga.milesplit.com/teams/4464-milton-high-school',
 'Mitchell County': 'https://ga.milesplit.com/teams/9051-mitchell-county',
 'Model': 'https://ga.milesplit.com/teams/6140-model',
 'Monroe Academy': 'https://ga.milesplit.com/teams/18965-monroe-academy',
 'Monroe Area High School': 'https://ga.milesplit.com/teams/4666-monroe-area-high-school',
 'Monroe Comprehensive High School': 'https://ga.milesplit.com/teams/4293-monroe-comprehensive-high-school',
 'Monsignor Donovan Catholic HS': 'https://ga.milesplit.com/teams/23737-monsignor-donovan-catholic-hs',
 'Montessori of Macon': 'https://ga.milesplit.com/teams/34810-montessori-of-macon',
 'Montgomery County HS': 'https://ga.milesplit.com/teams/9093-montgomery-county-hs',
 'Monticello HS': 'https://ga.milesplit.com/teams/51671-monticello-hs',
 'Monticello High School': 'https://ga.milesplit.com/teams/51672-monticello-high-school',
 'Morgan County HS': 'https://ga.milesplit.com/teams/7037-morgan-county-hs',
 'Morris Innovative High School': 'https://ga.milesplit.com/teams/30813-morris-innovative-high-school',
 'Morrow High School': 'https://ga.milesplit.com/teams/4290-morrow-high-school',
 'Mount Bethel Christian': 'https://ga.milesplit.com/teams/19010-mount-bethel-christian',
 'Mount De Sales': 'https://ga.milesplit.com/teams/12125-mount-de-sales',
 'Mount Paran Christian School': 'https://ga.milesplit.com/teams/9123-mount-paran-christian-school',
 'Mount Pisgah Christian School': 'https://ga.milesplit.com/teams/9124-mount-pisgah-christian-school',
 'Mount Vernon Christian': 'https://ga.milesplit.com/teams/57238-mount-vernon-christian',
 'Mount Zion High School': 'https://ga.milesplit.com/teams/4500-mount-zion-high-school',
 'Mountain Area Christian Academy': 'https://ga.milesplit.com/teams/41378-mountain-area-christian-academy',
 'Mountain View HS': 'https://ga.milesplit.com/teams/22973-mountain-view-hs',
 'Mt. Zion Carroll': 'https://ga.milesplit.com/teams/9107-mt-zion-carroll',
 'Mundys Mill High School': 'https://ga.milesplit.com/teams/4368-mundys-mill-high-school',
 'Murphy High School': 'https://ga.milesplit.com/teams/57241-murphy-high-school',
 'Murray County High School': 'https://ga.milesplit.com/teams/9017-murray-county-high-school',
 'NHND PREP ACADEMY': 'https://ga.milesplit.com/teams/52728-nhnd-prep-academy',
 'NHSTFXCCA': 'https://ga.milesplit.com/teams/66680-nhstfxcca',
 'NULL': 'https://ga.milesplit.com/teams/51160-null',
 'Nathanael Greene Academy': 'https://ga.milesplit.com/teams/18966-nathanael-greene-academy',
 'New Creation Christian Academy': 'https://ga.milesplit.com/teams/40546-new-creation-christian-academy',
 'New Hampstead HS': 'https://ga.milesplit.com/teams/30479-new-hampstead-hs',
 'New Horizons New Direction Preparatory Academy': 'https://ga.milesplit.com/teams/69949-new-horizons-new-direction-preparatory-academy',
 'New Manchester High School': 'https://ga.milesplit.com/teams/28198-new-manchester-high-school',
 'Newnan High School': 'https://ga.milesplit.com/teams/4445-newnan-high-school',
 'Newton': 'https://ga.milesplit.com/teams/4738-newton',
 'Nicholls High School': 'https://ga.milesplit.com/teams/57240-nicholls-high-school',
 'Noonday Park': 'https://ga.milesplit.com/teams/65339-noonday-park',
 'Norcross High School': 'https://ga.milesplit.com/teams/4304-norcross-high-school',
 'North Atlanta': 'https://ga.milesplit.com/teams/4683-north-atlanta',
 'North Atlanta Christian': 'https://ga.milesplit.com/teams/30547-north-atlanta-christian',
 'North Cherokee Wolfpack': 'https://ga.milesplit.com/teams/22316-north-cherokee-wolfpack',
 'North Clayton High School': 'https://ga.milesplit.com/teams/4668-north-clayton-high-school',
 'North Cobb Christian': 'https://ga.milesplit.com/teams/16398-north-cobb-christian',
 'North Cobb High School': 'https://ga.milesplit.com/teams/4451-north-cobb-high-school',
 'North Forsyth': 'https://ga.milesplit.com/teams/4670-north-forsyth',
 'North Fulton High School': 'https://ga.milesplit.com/teams/57230-north-fulton-high-school',
 'North Georgia Christian Academy': 'https://ga.milesplit.com/teams/43520-north-georgia-christian-academy',
 'North Georgia Christian School': 'https://ga.milesplit.com/teams/26904-north-georgia-christian-school',
 'North Gwinnett': 'https://ga.milesplit.com/teams/4364-north-gwinnett',
 'North Hall': 'https://ga.milesplit.com/teams/6168-north-hall',
 'North Henry Academy': 'https://ga.milesplit.com/teams/43498-north-henry-academy',
 'North Murray High School': 'https://ga.milesplit.com/teams/23042-north-murray-high-school',
 'North Oconee': 'https://ga.milesplit.com/teams/5977-north-oconee',
 'North Paulding HS': 'https://ga.milesplit.com/teams/15594-north-paulding-hs',
 'North Springs': 'https://ga.milesplit.com/teams/4329-north-springs',
 'Northeast Macon': 'https://ga.milesplit.com/teams/4651-northeast-macon',
 'Northgate': 'https://ga.milesplit.com/teams/4742-northgate',
 'Northside Columbus': 'https://ga.milesplit.com/teams/8351-northside-columbus',
 'Northside Warner Robins': 'https://ga.milesplit.com/teams/7133-northside-warner-robins',
 'Northview High School': 'https://ga.milesplit.com/teams/4373-northview-high-school',
 'Northwest Whitfield High School': 'https://ga.milesplit.com/teams/4246-northwest-whitfield-high-school',
 'Notre Dame Academy': 'https://ga.milesplit.com/teams/20449-notre-dame-academy',
 'Null': 'https://ga.milesplit.com/teams/68038-null',
 'Oak Hill Classical School': 'https://ga.milesplit.com/teams/30476-oak-hill-classical-school',
 'Oak Mountain Academy': 'https://ga.milesplit.com/teams/28917-oak-mountain-academy',
 'Oakwood Academy': 'https://ga.milesplit.com/teams/30816-oakwood-academy',
 'Oconee County High School': 'https://ga.milesplit.com/teams/4301-oconee-county-high-school',
 'Oglethorpe County HS': 'https://ga.milesplit.com/teams/7025-oglethorpe-county-hs',
 'Ola High School': 'https://ga.milesplit.com/teams/9046-ola-high-school',
 'Old Suwanee Christian School': 'https://ga.milesplit.com/teams/26002-old-suwanee-christian-school',
 'Osborne High School': 'https://ga.milesplit.com/teams/4454-osborne-high-school',
 'Osbourne HS': 'https://ga.milesplit.com/teams/51668-osbourne-hs',
 'Osbourne High School': 'https://ga.milesplit.com/teams/51669-osbourne-high-school',
 'Our Lady of Mercy High School': 'https://ga.milesplit.com/teams/57253-our-lady-of-mercy-high-school',
 'Pace Academy': 'https://ga.milesplit.com/teams/5946-pace-academy',
 'Paideia': 'https://ga.milesplit.com/teams/9067-paideia',
 'Panther Pride': 'https://ga.milesplit.com/teams/21263-panther-pride',
 'Parkview High School': 'https://ga.milesplit.com/teams/4452-parkview-high-school',
 'Pataula Charter Academy': 'https://ga.milesplit.com/teams/31235-pataula-charter-academy',
 'Paulding County': 'https://ga.milesplit.com/teams/6165-paulding-county',
 'Peach Co.': 'https://ga.milesplit.com/teams/4650-peach-co',
 'Peachtree Academy': 'https://ga.milesplit.com/teams/40478-peachtree-academy',
 'Peachtree Ridge High School': 'https://ga.milesplit.com/teams/4467-peachtree-ridge-high-school',
 'Pebblebrook High School': 'https://ga.milesplit.com/teams/4457-pebblebrook-high-school',
 'Pelham High School': 'https://ga.milesplit.com/teams/7094-pelham-high-school',
 'Peoples Baptist Academy': 'https://ga.milesplit.com/teams/50499-peoples-baptist-academy',
 'Pepperell High School': 'https://ga.milesplit.com/teams/6137-pepperell-high-school',
 'Perry High School': 'https://ga.milesplit.com/teams/8379-perry-high-school',
 'Philadelphia Christian School': 'https://ga.milesplit.com/teams/68078-philadelphia-christian-school',
 'Pickens': 'https://ga.milesplit.com/teams/7673-pickens',
 'Piedmont Academy': 'https://ga.milesplit.com/teams/26034-piedmont-academy',
 'Pierce County HS': 'https://ga.milesplit.com/teams/9056-pierce-county-hs',
 'Pike County High School': 'https://ga.milesplit.com/teams/7680-pike-county-high-school',
 'Pinecrest Academy': 'https://ga.milesplit.com/teams/12126-pinecrest-academy',
 'Pinewood Christian': 'https://ga.milesplit.com/teams/25888-pinewood-christian',
 'Pope High School': 'https://ga.milesplit.com/teams/4167-pope-high-school',
 'Portal': 'https://ga.milesplit.com/teams/9097-portal',
 'Praise Academy': 'https://ga.milesplit.com/teams/38873-praise-academy',
 'Premier Athletics Track & Field Club': 'https://ga.milesplit.com/teams/29267-premier-athletics-track-and-field-club',
 'Prince Avenue Christian School': 'https://ga.milesplit.com/teams/9128-prince-avenue-christian-school',
 'Promise Prep': 'https://ga.milesplit.com/teams/51867-promise-prep',
 'Providence Christian Academy': 'https://ga.milesplit.com/teams/4499-providence-christian-academy',
 'Providence Classical Christian School': 'https://ga.milesplit.com/teams/40526-providence-classical-christian-school',
 'Putnam County HS': 'https://ga.milesplit.com/teams/9072-putnam-county-hs',
 'Quitman County HS': 'https://ga.milesplit.com/teams/26777-quitman-county-hs',
 'Rabun County': 'https://ga.milesplit.com/teams/9075-rabun-county',
 'Rainey McCullers School of the Arts': 'https://ga.milesplit.com/teams/56090-rainey-mccullers-school-of-the-arts',
 'Randolph Southern School': 'https://ga.milesplit.com/teams/15932-randolph-southern-school',
 'Randolph-Clay HS': 'https://ga.milesplit.com/teams/9052-randolph-clay-hs',
 'Rate of Motion Elite Track Club': 'https://ga.milesplit.com/teams/19869-rate-of-motion-elite-track-club',
 'Red Bud High School': 'https://ga.milesplit.com/teams/57246-red-bud-high-school',
 'Redan High School': 'https://ga.milesplit.com/teams/4302-redan-high-school',
 'Richmond Academy': 'https://ga.milesplit.com/teams/7106-richmond-academy',
 'Richmond County Technical Career Magnet School': 'https://ga.milesplit.com/teams/36266-richmond-county-technical-career-magnet-school',
 'Richmond Hill': 'https://ga.milesplit.com/teams/9040-richmond-hill',
 'Ridgeland': 'https://ga.milesplit.com/teams/8469-ridgeland',
 'Ringgold High School': 'https://ga.milesplit.com/teams/4872-ringgold-high-school',
 'River Ridge HS': 'https://ga.milesplit.com/teams/23283-river-ridge-hs',
 'Riverdale High School': 'https://ga.milesplit.com/teams/4369-riverdale-high-school',
 'Rivers Academy': 'https://ga.milesplit.com/teams/45324-rivers-academy',
 'Riverside Military Academy': 'https://ga.milesplit.com/teams/16397-riverside-military-academy',
 'Riverwood International Charter School': 'https://ga.milesplit.com/teams/4443-riverwood-international-charter-school',
 'Robert Toombs Christian School': 'https://ga.milesplit.com/teams/23736-robert-toombs-christian-school',
 'Rock Springs Christian Academy': 'https://ga.milesplit.com/teams/36208-rock-springs-christian-academy',
 'Rockdale Co.': 'https://ga.milesplit.com/teams/4476-rockdale-co',
 'Rockmart High School': 'https://ga.milesplit.com/teams/5874-rockmart-high-school',
 'Rome High School': 'https://ga.milesplit.com/teams/4604-rome-high-school',
 'Roswell High School': 'https://ga.milesplit.com/teams/4169-roswell-high-school',
 'Rustenburg High School SA': 'https://ga.milesplit.com/teams/62276-rustenburg-high-school-sa',
 'Rutland High School': 'https://ga.milesplit.com/teams/9064-rutland-high-school',
 'Salem High School': 'https://ga.milesplit.com/teams/5878-salem-high-school',
 'Sandy Creek': 'https://ga.milesplit.com/teams/4458-sandy-creek',
 'Savannah Arts Academy': 'https://ga.milesplit.com/teams/7692-savannah-arts-academy',
 'Savannah Christian Prep': 'https://ga.milesplit.com/teams/9057-savannah-christian-prep',
 'Savannah Classical Academy': 'https://ga.milesplit.com/teams/39020-savannah-classical-academy',
 'Savannah Country Day School': 'https://ga.milesplit.com/teams/6169-savannah-country-day-school',
 'Savannah Early College': 'https://ga.milesplit.com/teams/39196-savannah-early-college',
 'Savannah HS': 'https://ga.milesplit.com/teams/9031-savannah-hs',
 'Schley County High': 'https://ga.milesplit.com/teams/7095-schley-county-high',
 'School for Arts-Infused Learning': 'https://ga.milesplit.com/teams/45657-school-for-arts-infused-learning',
 'Screven Christian Academy': 'https://ga.milesplit.com/teams/54184-screven-christian-academy',
 'Screven County': 'https://ga.milesplit.com/teams/7100-screven-county',
 'Seckinger High School': 'https://ga.milesplit.com/teams/54539-seckinger-high-school',
 'Seminole County HS': 'https://ga.milesplit.com/teams/9081-seminole-county-hs',
 'Sequoyah High School': 'https://ga.milesplit.com/teams/4332-sequoyah-high-school',
 'Sequoyah Youth Track Club': 'https://ga.milesplit.com/teams/21272-sequoyah-youth-track-club',
 'Shamrock High School': 'https://ga.milesplit.com/teams/57235-shamrock-high-school',
 'Shaw High School': 'https://ga.milesplit.com/teams/6885-shaw-high-school',
 'Sherwood Christian': 'https://ga.milesplit.com/teams/23741-sherwood-christian',
 'Shiloh High School': 'https://ga.milesplit.com/teams/4166-shiloh-high-school',
 'Shiloh Hills Christian School': 'https://ga.milesplit.com/teams/41217-shiloh-hills-christian-school',
 'Sinclair Christian Academy': 'https://ga.milesplit.com/teams/29126-sinclair-christian-academy',
 'Skipstone Academy': 'https://ga.milesplit.com/teams/41497-skipstone-academy',
 'Social Circle High School': 'https://ga.milesplit.com/teams/8353-social-circle-high-school',
 'Sonoraville HS': 'https://ga.milesplit.com/teams/9070-sonoraville-hs',
 'South Atlanta': 'https://ga.milesplit.com/teams/6913-south-atlanta',
 'South Cobb': 'https://ga.milesplit.com/teams/4455-south-cobb',
 'South Effingham High School': 'https://ga.milesplit.com/teams/9042-south-effingham-high-school',
 'South Forsyth High School': 'https://ga.milesplit.com/teams/4363-south-forsyth-high-school',
 'South Gwinnett': 'https://ga.milesplit.com/teams/4498-south-gwinnett',
 'South Paulding HS': 'https://ga.milesplit.com/teams/9034-south-paulding-hs',
 'Southeast Bulloch': 'https://ga.milesplit.com/teams/4630-southeast-bulloch',
 'Southeast High School': 'https://ga.milesplit.com/teams/57255-southeast-high-school',
 'Southeast Whitfield High School': 'https://ga.milesplit.com/teams/6896-southeast-whitfield-high-school',
 'Southland Academy': 'https://ga.milesplit.com/teams/19551-southland-academy',
 'Southwest Atlanta Christian': 'https://ga.milesplit.com/teams/9118-southwest-atlanta-christian',
 'Southwest Dekalb': 'https://ga.milesplit.com/teams/4331-southwest-dekalb',
 'Southwest Georgia Academy': 'https://ga.milesplit.com/teams/15930-southwest-georgia-academy',
 'Southwest Georgia Homeschool Association': 'https://ga.milesplit.com/teams/45344-southwest-georgia-homeschool-association',
 'Southwest Georgia STEM Charter High School': 'https://ga.milesplit.com/teams/53517-southwest-georgia-stem-charter-high-school',
 'Southwest Macon': 'https://ga.milesplit.com/teams/8349-southwest-macon',
 'Spalding High School': 'https://ga.milesplit.com/teams/4283-spalding-high-school',
 'SpeedTech Track Club': 'https://ga.milesplit.com/teams/33733-speedtech-track-club',
 'Spencer High School': 'https://ga.milesplit.com/teams/47281-spencer-high-school',
 'Sprayberry High School': 'https://ga.milesplit.com/teams/4456-sprayberry-high-school',
 'Springmont School': 'https://ga.milesplit.com/teams/49207-springmont-school',
 'St. Andrews School': 'https://ga.milesplit.com/teams/28890-st-andrews-school',
 'St. Anne Pacelli Catholic School': 'https://ga.milesplit.com/teams/18793-st-anne-pacelli-catholic-school',
 'St. Francis': 'https://ga.milesplit.com/teams/9125-st-francis',
 "St. George's Episcopal School": 'https://ga.milesplit.com/teams/18722-st-georges-episcopal-school',
 'St. John Bosco Academy': 'https://ga.milesplit.com/teams/40527-st-john-bosco-academy',
 'St. Martins Episcopal School': 'https://ga.milesplit.com/teams/18933-st-martins-episcopal-school',
 "St. Mary's Academy": 'https://ga.milesplit.com/teams/4440-st-marys-academy',
 'St. Pius X': 'https://ga.milesplit.com/teams/4441-st-pius-x',
 "St. Vincent's Academy  (SVA)": 'https://ga.milesplit.com/teams/9041-st-vincents-academy-sva',
 'Starrs Mill High School': 'https://ga.milesplit.com/teams/4295-starrs-mill-high-school',
 'Statesboro High School': 'https://ga.milesplit.com/teams/4172-statesboro-high-school',
 'Stephens Co.': 'https://ga.milesplit.com/teams/4658-stephens-co',
 'Stephenson High School': 'https://ga.milesplit.com/teams/4291-stephenson-high-school',
 'Stewart County HS': 'https://ga.milesplit.com/teams/9103-stewart-county-hs',
 'Stilwell HS': 'https://ga.milesplit.com/teams/37096-stilwell-hs',
 'Stockbridge High School': 'https://ga.milesplit.com/teams/4374-stockbridge-high-school',
 'Stone Mountain HS': 'https://ga.milesplit.com/teams/4376-stone-mountain-hs',
 'Stratford Academy': 'https://ga.milesplit.com/teams/7650-stratford-academy',
 'Strong Rock Christian School': 'https://ga.milesplit.com/teams/18963-strong-rock-christian-school',
 'Strong Wall Academy': 'https://ga.milesplit.com/teams/43897-strong-wall-academy',
 'Sumter County High School': 'https://ga.milesplit.com/teams/4495-sumter-county-high-school',
 'Swainsboro High School': 'https://ga.milesplit.com/teams/8367-swainsboro-high-school',
 'Sylvan High School': 'https://ga.milesplit.com/teams/57226-sylvan-high-school',
 'THRIVE Christian Academy': 'https://ga.milesplit.com/teams/44553-thrive-christian-academy',
 'Taliaferro County': 'https://ga.milesplit.com/teams/9117-taliaferro-county',
 'Tallulah Falls': 'https://ga.milesplit.com/teams/4745-tallulah-falls',
 'Tapestry Public Charter School': 'https://ga.milesplit.com/teams/38993-tapestry-public-charter-school',
 'Tattnall County High School': 'https://ga.milesplit.com/teams/8365-tattnall-county-high-school',
 'Tattnall Square Academy': 'https://ga.milesplit.com/teams/18960-tattnall-square-academy',
 'Taylor County HS': 'https://ga.milesplit.com/teams/9102-taylor-county-hs',
 'Tech Charter': 'https://ga.milesplit.com/teams/9121-tech-charter',
 'Telfair County HS': 'https://ga.milesplit.com/teams/9094-telfair-county-hs',
 'Temple High School': 'https://ga.milesplit.com/teams/8371-temple-high-school',
 'Terra at Serenbe': 'https://ga.milesplit.com/teams/56342-terra-at-serenbe',
 'Terrell Academy': 'https://ga.milesplit.com/teams/15472-terrell-academy',
 'Terrell County HS': 'https://ga.milesplit.com/teams/9082-terrell-county-hs',
 'The Barnes Academy': 'https://ga.milesplit.com/teams/37140-the-barnes-academy',
 'The Bedford School': 'https://ga.milesplit.com/teams/67984-the-bedford-school',
 'The Campus': 'https://ga.milesplit.com/teams/49055-the-campus',
 'The Cottage School': 'https://ga.milesplit.com/teams/12127-the-cottage-school',
 'The Dalton Academy': 'https://ga.milesplit.com/teams/53665-the-dalton-academy',
 'The Dinoff School': 'https://ga.milesplit.com/teams/43402-the-dinoff-school',
 'The Heritage School': 'https://ga.milesplit.com/teams/48833-the-heritage-school',
 'The Howard School': 'https://ga.milesplit.com/teams/25795-the-howard-school',
 "The King's Academy": 'https://ga.milesplit.com/teams/18968-the-kings-academy',
 'The Kings Academy': 'https://ga.milesplit.com/teams/50438-the-kings-academy',
 'The LIFE School': 'https://ga.milesplit.com/teams/47368-the-life-school',
 'The Mount Vernon School': 'https://ga.milesplit.com/teams/25871-the-mount-vernon-school',
 'The Shift Academy': 'https://ga.milesplit.com/teams/49104-the-shift-academy',
 'The Stonehaven School': 'https://ga.milesplit.com/teams/40518-the-stonehaven-school',
 'The Weber School': 'https://ga.milesplit.com/teams/20281-the-weber-school',
 'The Wilson Academy': 'https://ga.milesplit.com/teams/38223-the-wilson-academy',
 'Therrell': 'https://ga.milesplit.com/teams/4471-therrell',
 'Thomas County Central High School': 'https://ga.milesplit.com/teams/4527-thomas-county-central-high-school',
 'Thomas Jefferson Academy': 'https://ga.milesplit.com/teams/26371-thomas-jefferson-academy',
 'Thomasville High School': 'https://ga.milesplit.com/teams/7714-thomasville-high-school',
 'Thomson High School/ Middle School': 'https://ga.milesplit.com/teams/4447-thomson-high-school-middle-school',
 'Throw1deep': 'https://ga.milesplit.com/teams/19885-throw1deep',
 'Tift Area Academy': 'https://ga.milesplit.com/teams/15443-tift-area-academy',
 'Tift County High School': 'https://ga.milesplit.com/teams/4494-tift-county-high-school',
 'Tiftarea Academy HS': 'https://ga.milesplit.com/teams/69312-tiftarea-academy-hs',
 'Toombs County HS': 'https://ga.milesplit.com/teams/9060-toombs-county-hs',
 'Towers High School': 'https://ga.milesplit.com/teams/4472-towers-high-school',
 'Towns County HS': 'https://ga.milesplit.com/teams/9131-towns-county-hs',
 'Treutlen': 'https://ga.milesplit.com/teams/7056-treutlen',
 'Tri Cities': 'https://ga.milesplit.com/teams/4446-tri-cities',
 'Tri-County': 'https://ga.milesplit.com/teams/9065-tri-county',
 'Trinity Christian Griffin': 'https://ga.milesplit.com/teams/25958-trinity-christian-griffin',
 'Trinity Christian MS': 'https://ga.milesplit.com/teams/68476-trinity-christian-ms',
 'Trinity Christian Midle School': 'https://ga.milesplit.com/teams/68477-trinity-christian-midle-school',
 'Trinity Christian Sharpsburg': 'https://ga.milesplit.com/teams/28934-trinity-christian-sharpsburg',
 'Trinity Christian Statesboro': 'https://ga.milesplit.com/teams/43690-trinity-christian-statesboro',
 'Trinity Classical School': 'https://ga.milesplit.com/teams/18794-trinity-classical-school',
 'Trinity Dublin Christian School': 'https://ga.milesplit.com/teams/18961-trinity-dublin-christian-school',
 'Trinity MS': 'https://ga.milesplit.com/teams/68473-trinity-ms',
 'Trinity Prep Middle School': 'https://ga.milesplit.com/teams/56890-trinity-prep-middle-school',
 'Trinity Prep School': 'https://ga.milesplit.com/teams/56889-trinity-prep-school',
 'Trion': 'https://ga.milesplit.com/teams/9108-trion',
 'Troup Co.': 'https://ga.milesplit.com/teams/4679-troup-co',
 'Tucker': 'https://ga.milesplit.com/teams/4656-tucker',
 'Turner County HS': 'https://ga.milesplit.com/teams/9091-turner-county-hs',
 'Twiggs Academy': 'https://ga.milesplit.com/teams/26374-twiggs-academy',
 'Twiggs County': 'https://ga.milesplit.com/teams/7093-twiggs-county',
 'Union County HS': 'https://ga.milesplit.com/teams/9076-union-county-hs',
 'Union Grove HS': 'https://ga.milesplit.com/teams/4442-union-grove-hs',
 'Unity Christian School': 'https://ga.milesplit.com/teams/26957-unity-christian-school',
 'Upson-Lee High School': 'https://ga.milesplit.com/teams/7639-upson-lee-high-school',
 'Urban Christian Academy': 'https://ga.milesplit.com/teams/44516-urban-christian-academy',
 'Utopian Academy For the Arts': 'https://ga.milesplit.com/teams/54669-utopian-academy-for-the-arts',
 'VE Trck Club -GA': 'https://ga.milesplit.com/teams/15406-ve-trck-club-ga',
 'Valdosta High School': 'https://ga.milesplit.com/teams/4669-valdosta-high-school',
 'Valor Christian Academy': 'https://ga.milesplit.com/teams/36318-valor-christian-academy',
 'Valwood School': 'https://ga.milesplit.com/teams/15931-valwood-school',
 'Veritas Academy': 'https://ga.milesplit.com/teams/39149-veritas-academy',
 'Veterans HS': 'https://ga.milesplit.com/teams/26734-veterans-hs',
 'Vidalia': 'https://ga.milesplit.com/teams/8364-vidalia',
 'Vidalia Heritage Academy': 'https://ga.milesplit.com/teams/34781-vidalia-heritage-academy',
 'Villa Rica': 'https://ga.milesplit.com/teams/4678-villa-rica',
 'W.D. Mohammed': 'https://ga.milesplit.com/teams/9122-wd-mohammed',
 'Walker': 'https://ga.milesplit.com/teams/4502-walker',
 'Walnut Grove HS': 'https://ga.milesplit.com/teams/23000-walnut-grove-hs',
 'Walton High School': 'https://ga.milesplit.com/teams/528-walton-high-school',
 'Ware County High School': 'https://ga.milesplit.com/teams/9021-ware-county-high-school',
 'Ware County Magnet HS': 'https://ga.milesplit.com/teams/9088-ware-county-magnet-hs',
 'Warner Robins': 'https://ga.milesplit.com/teams/5920-warner-robins',
 'Warren County High School': 'https://ga.milesplit.com/teams/8355-warren-county-high-school',
 'Washington County': 'https://ga.milesplit.com/teams/7102-washington-county',
 'Washington-Wilkes High School': 'https://ga.milesplit.com/teams/8356-washington-wilkes-high-school',
 'Wayne Christian Academy HS': 'https://ga.milesplit.com/teams/56830-wayne-christian-academy-hs',
 'Wayne County HS': 'https://ga.milesplit.com/teams/9033-wayne-county-hs',
 'Webster County HS': 'https://ga.milesplit.com/teams/15962-webster-county-hs',
 'Wesleyan School': 'https://ga.milesplit.com/teams/4468-wesleyan-school',
 'West Forsyth High School': 'https://ga.milesplit.com/teams/7723-west-forsyth-high-school',
 'West Hall High School': 'https://ga.milesplit.com/teams/7681-west-hall-high-school',
 'West Laurens High School': 'https://ga.milesplit.com/teams/7054-west-laurens-high-school',
 'West Rome High School': 'https://ga.milesplit.com/teams/57244-west-rome-high-school',
 'Westfield School': 'https://ga.milesplit.com/teams/23747-westfield-school',
 'Westlake': 'https://ga.milesplit.com/teams/4303-westlake',
 'Westminster Christian Academy': 'https://ga.milesplit.com/teams/23743-westminster-christian-academy',
 'Westminster School': 'https://ga.milesplit.com/teams/4488-westminster-school',
 'Westminster Schools of Augusta': 'https://ga.milesplit.com/teams/28889-westminster-schools-of-augusta',
 'Westover High School': 'https://ga.milesplit.com/teams/4294-westover-high-school',
 'Westside Augusta': 'https://ga.milesplit.com/teams/4449-westside-augusta',
 'Westside Macon': 'https://ga.milesplit.com/teams/7108-westside-macon',
 'Westwood Christian Academy': 'https://ga.milesplit.com/teams/40539-westwood-christian-academy',
 'Westwood Schools': 'https://ga.milesplit.com/teams/15444-westwood-schools',
 'Wheeler County HS': 'https://ga.milesplit.com/teams/9095-wheeler-county-hs',
 'Wheeler High School': 'https://ga.milesplit.com/teams/4327-wheeler-high-school',
 'Whigham High School': 'https://ga.milesplit.com/teams/57231-whigham-high-school',
 'White County High School': 'https://ga.milesplit.com/teams/4469-white-county-high-school',
 'Whitefield Academy': 'https://ga.milesplit.com/teams/4677-whitefield-academy',
 'Whitewater High School': 'https://ga.milesplit.com/teams/5937-whitewater-high-school',
 'Wilcox County': 'https://ga.milesplit.com/teams/9092-wilcox-county',
 'Wilcox MS': 'https://ga.milesplit.com/teams/51461-wilcox-ms',
 'Wildwood Christian Academy': 'https://ga.milesplit.com/teams/30533-wildwood-christian-academy',
 'Wilkinson County HS': 'https://ga.milesplit.com/teams/9113-wilkinson-county-hs',
 'William & Reed Academy': 'https://ga.milesplit.com/teams/40540-william-and-reed-academy',
 'William H. Spencer High School': 'https://ga.milesplit.com/teams/9038-william-h-spencer-high-school',
 'Winder-Barrow HS': 'https://ga.milesplit.com/teams/18884-winder-barrow-hs',
 'Windsor Academy': 'https://ga.milesplit.com/teams/31712-windsor-academy',
 'Windsor Forest': 'https://ga.milesplit.com/teams/9032-windsor-forest',
 'Woodland': 'https://ga.milesplit.com/teams/6166-woodland',
 'Woodland HS Stockbridge': 'https://ga.milesplit.com/teams/10705-woodland-hs-stockbridge',
 'Woodstock High School': 'https://ga.milesplit.com/teams/4168-woodstock-high-school',
 'Woodville-Tompkins HS': 'https://ga.milesplit.com/teams/30480-woodville-tompkins-hs',
 'Woodward Academy': 'https://ga.milesplit.com/teams/4463-woodward-academy',
 'Woody Gap': 'https://ga.milesplit.com/teams/9132-woody-gap',
 'Worth County HS': 'https://ga.milesplit.com/teams/9037-worth-county-hs',
 'Wrens High School': 'https://ga.milesplit.com/teams/57232-wrens-high-school',
 'Yeshiva': 'https://ga.milesplit.com/teams/9126-yeshiva',
 'Young Americans Christian School': 'https://ga.milesplit.com/teams/26901-young-americans-christian-school',
 'null': 'https://ga.milesplit.com/teams/62589-null'}